/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: AleixoAlonso (https://sketchfab.com/AleixoAlonso)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-light-bulb-a7d27c2224d94c86a04083de8f9df7db
Title: Low Poly Light Bulb
*/

import { useGLTF } from '@react-three/drei'

export  function Bulb(props) {
  const { nodes, materials } = useGLTF('model/low_poly_light_bulb.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['#LMP0003_Light_Bulb_Low_Poly_#LMP0003_Textures_0'].geometry}
        material={materials.LMP0003_Textures}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  )
}

useGLTF.preload('model/low_poly_light_bulb.glb')