/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

'use client'

import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('model/SPACEmodel.glb')
  return (
    <group {...props} dispose={null} rotation={[0,Math.PI/0.72,0]} position={[ 0, -.75, 0]}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Torus074.geometry}
        material={materials['Material.001']}
        position={[0.332, 0.284, 0.17]}
        rotation={[2.238, -0.492, -1.161]}
        scale={[0.518, 0.592, 0.429]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Torus081.geometry}
        material={materials['Material.001']}
        position={[0.332, 0.284, 0.17]}
        rotation={[2.238, -0.492, -1.161]}
        scale={[0.518, 0.592, 0.429]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Torus096.geometry}
        material={materials['Material.001']}
        position={[0.332, 0.284, 0.17]}
        rotation={[2.238, -0.492, -1.161]}
        scale={[0.518, 0.592, 0.429]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Torus105.geometry}
        material={materials['Material.001']}
        position={[0.332, 0.284, 0.17]}
        rotation={[2.238, -0.492, -1.161]}
        scale={[0.518, 0.592, 0.429]}
      />
      <group
        position={[0.332, 0.284, 0.17]}
        rotation={[2.238, -0.492, -1.161]}
        scale={[0.518, 0.592, 0.429]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Torus149.geometry}
          material={materials['Material.023']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Torus149_1.geometry}
          material={materials['Material.008']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Torus149_2.geometry}
          material={materials['Material.009']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Torus149_3.geometry}
          material={materials['Material.022']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Torus149_4.geometry}
          material={materials['Material.015']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Torus149_5.geometry}
          material={materials['Material.014']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Torus149_6.geometry}
          material={materials['Material.013']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Torus149_7.geometry}
          material={materials['Material.018']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Torus149_8.geometry}
          material={materials['Material.016']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Torus149_9.geometry}
          material={materials['Material.019']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Torus149_10.geometry}
          material={nodes.Torus149_10.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Torus149_11.geometry}
          material={materials['Material.012']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Torus149_12.geometry}
          material={materials['Material.005']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Torus149_13.geometry}
          material={materials.Material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Torus149_14.geometry}
          material={materials['Material.010']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Torus149_15.geometry}
          material={materials['Material.011']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Torus149_16.geometry}
          material={materials['Material.025']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Torus149_17.geometry}
          material={materials['Material.026']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Torus149_18.geometry}
          material={materials['Material.024']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Torus149_19.geometry}
          material={materials['Material.021']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Torus149_20.geometry}
          material={materials['Material.020']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Torus149_21.geometry}
          material={materials['Material.004']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Torus149_22.geometry}
          material={materials['Material.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Torus149_23.geometry}
          material={materials['Material.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Torus149_24.geometry}
          material={materials['Material.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Torus149_25.geometry}
          material={materials['Material.006']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Torus149_26.geometry}
          material={materials['Material.007']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Torus088.geometry}
        material={materials['Material.001']}
        position={[0.332, 0.284, 0.17]}
        rotation={[2.238, -0.492, -1.161]}
        scale={[0.518, 0.592, 0.429]}
      />
    </group>
  )
}

useGLTF.preload('model/SPACEmodel.glb')